# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'alternative'
      MYSQL_USER: 'ayalon'
      MYSQL_PASSWORD: 'emp_pass'
      MYSQL_ROOT_PASSWORD: 'adm_emp'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql  
  node_server:
    build:
      context: ./server
      dockerfile: dockerfile_server.dev
    ports:
      - 5000:5000
    volumes:
      - /server/node_modules
      - ./server:/server
    environment: 
      - mysql_server=mysql
      - NODE_ENV=development
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    command: ["npm", "start"] 
  node_server_test:
    build:
      context: ./server
      dockerfile: dockerfile_server.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 5050:5000
    environment: 
      - mysql_server=mysql
      - NODE_ENV=test
    stdin_open: true
    tty: true
    command: ["npm", "test"]
  alternative:
    build:
      context: ./client
      dockerfile: dockerfile_app.dev
    ports: 
      - "3000:3000"
    volumes:
      # - /app/node_modules
      - ./client:/client
    stdin_open: true
    tty: true
    depends_on:
      - node_server
    command: ["npm", "start"]
  nginx:
    build:
      dockerfile: dockerfile_nginx.dev
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - alternative
      - node_server
volumes:
  db-data:
    driver: local
  
