# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
  clustering:
    image: nativelaasakimcr.azurecr.io/clustering
    volumes:
      - /clustering/node_modules
      - /clustering
      - logs_dir:/clustering/logs
    restart: always
    stdin_open: true
    tty: true
    command: ["npm", "run", "start"] 
  node_server:
    image: nativelaasakimcr.azurecr.io/node_server
    environment:
      - mysql_server=mysql
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - secert=${secret}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CLUSTERING_SERVER=clustering
    volumes:
      - /server
      - /server/node_modules
      - logs_dir:/server/logs
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    command: ["npm", "start"]
  native_laasakim:
    image: nativelaasakimcr.azurecr.io/native_laasakim
    environment:
      - REACT_APP_SERVER=${SERVER}
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - node_server
  nginx:
    mage: nativelaasakimcr.azurecr.io/nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - native_laasakim
      - node_server
    restart: always
    volumes:
      - ./secret:/etc/nginx/certs
      - logs_dir:/spool/logs
  volumes:
    db-data:
      driver: local
      driver_opts:
        o: bind
        type: None
        device: /home/NativeLaasakimAH/datadrive/db-data
    logs_dir:
      driver: local
      driver_opts:
        o: bind
        type: None
        device: /home/NativeLaasakimAH/datadrive/logs
      