# docker-compose.yml
version: '3'  
services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: true
    tty: true
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes: 
      - db-data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
  clustering:
    build:
      context: ./clustering
      dockerfile: dockerfile_clustering
    volumes:
      - /clustering/node_modules
      - /clustering
      - ./clustering/logs:/clustering/logs
    environment:
      - PORT=${CLUSTERING_PORT}
    restart: always
    stdin_open: true
    tty: true
    command: ["npm", "run", "start"] 
  node_server:
    build:
      context: ./server
      dockerfile: dockerfile_server.dev
    volumes:
      - ./server/node_modules:/server/node_modules
      - ./server:/server
    #  - /server/node_modules
    #  - /server
    environment: 
      - mysql_server=mysql
      - NODE_ENV=development
      - CLUSTERING_SERVER=clustering
      - CLUSTERING_PORT=3500
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - mysql
      - clustering
    command: ["npm", "run", "dev"] 
  node_server_test:
    build:
      context: ./server
      dockerfile: dockerfile_server.dev
    volumes:
      - /app/node_modules
      - ./server:/app
#    ports:
#      - 5050:5000
    environment: 
      - mysql_server=mysql
      - NODE_ENV=test
    stdin_open: true
    tty: true
    command: ["npm", "test"]
  native_laasakim_dev:
    environment:
      - REACT_APP_SERVER=${SERVER}
    build:
      context: ./client
      dockerfile: dockerfile_app.dev
    volumes:
      - ./client/node_modules:/client/node_modules
      - ./client:/client
    #  - /client/node_modules
    #  - /client
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - node_server
    command: ["npm", "start"]
  native_laasakim:
    environment:
      - REACT_APP_SERVER=ayalon.promise-dev.com
    build:
      context: ./client
      dockerfile: .dockerfile
      args:
        - REACT_APP_SERVER=ayalon.promise-dev.com
    stdin_open: true
    tty: true
    depends_on:
      - node_server
  nginx_dev:
    build:
      dockerfile: dockerfile_nginx.dev
      context: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - native_laasakim_dev
      - node_server
    volumes: 
      - ./secret:/etc/nginx/certs
      - node_logs:/spool/logs
      - pdf_files:/www/pdf
  nginx:
    build:
      dockerfile: dockerfile_nginx.dev
      context: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - native_laasakim
      - node_server
    volumes: 
      - ./secret:/etc/nginx/certs
      - node_logs:/spool/logs
      - pdf_files:/www/pdf
volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: None
      device: /home/amit/workspace/employers_program/db-data
  node_logs:
    driver: local
    driver_opts:
      o: bind
      type: None
      device: ./server/logs
  pdf_files:
    driver: local
    driver_opts:
      o: bind
      type: None
      device: ./pdf
  
