# docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql  
  node_server:
    build:
      context: ./server
      dockerfile: dockerfile_server.dev
#    volumes:
#      - /server/node_modules
#      - ./server:/server
    environment: 
      - mysql_server=mysql
      - NODE_ENV=development
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    command: ["npm", "start"] 
  node_server_test:
    build:
      context: ./server
      dockerfile: dockerfile_server.dev
    volumes:
      - /app/node_modules
      - ./server:/app
#    ports:
#      - 5050:5000
    environment: 
      - mysql_server=mysql
      - NODE_ENV=test
    stdin_open: true
    tty: true
    command: ["npm", "test"]
  native_laasakim_dev:
    build:
      context: ./client
      dockerfile: dockerfile_app.dev
    volumes:
       - ./client/node_modules:/app/node_modules
       - ./client:/client
    stdin_open: true
    tty: true
    depends_on:
      - node_server
    command: ["npm", "start"]
  native_laasakim:
    build:
      context: ./client
      dockerfile: .dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - node_server
  nginx_dev:
    build:
      dockerfile: dockerfile_nginx.dev
      context: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - native_laasakim_dev
      - node_server
    volumes: 
      - ./secret:/etc/nginx/certs
  nginx:
    build:
      dockerfile: dockerfile_nginx.dev
      context: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - native_laasakim
      - node_server
    volumes: 
      - ./secret:/etc/nginx/certs
volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: None
      device: /home/amit/workspace/employers_program/db-data
  
