FROM node:alpine

WORKDIR '/server'

COPY ./package.json .
RUN npm install

#RUN apk update
#RUN apk add --no-cache make gcc g++ python && \
#  npm install && \
#  npm rebuild bcrypt --build-from-source && \
# apk del make gcc g++ python

COPY . .

CMD ["npm", "run", "start"]