FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./error/404.html /usr/share/nginx/html
COPY ./error/50x.html /usr/share/nginx/html
RUN mkdir -p /usr/share/nginx/html/pictures
COPY ./error/n_masikim.jpg /usr/share/nginx/html/pictures