export const AUTH_USER = 'auth_user';
export const AUTH_ERROR = 'auth_error';
export const FILE_UPLOAD = 'file_upload';
export const LOAD_DATA = 'load_data';
export const ADD_NEW_COMPANY = 'new_company';
export const EMPLOYEES_DATA = 'employees_data';
export const CHECK_PROGRESS = 'check_progress';
export const GENERAL_REPORT_RESULT = 'general_report_result';
export const GENERAL_REPORT_RUN = 'general_report_run'; // flag if general report is running
export const CLUSTER_REPORT_RESULT = 'cluster_report_result';
export const CLUSTER_REPORT_RUN = 'cluster_report_run'; // flag if cluster report calculation is running
export const SETTLEMENT_LIST = 'settlement_list';
export const SHARE_POTENTIAL = 'share_potential';
export const TIME_SLOT_TO_WORK = 'timeSlot_work_list'; //from server
export const TIME_SLOT_TO_HOME = 'timeSlot_home_list'; //from server
export const QUERY_LIVING_CITY = 'query_living_city'; // selected living cities for query
export const QUERY_WORKING_CITY = 'query_working_city'; // selected working cities for query
export const QUERY_COMPANY = 'query_company';  // selected companies for query
export const QUERY_TIME_SLOT_WORK = 'query_time_slot_work'; // time slots selected by user to query upon
export const QUERY_TIME_SLOT_HOME = 'query_time_slot_home'; // time slots selected by user to query upon
export const QUERY_STARTING_POLYGON = 'selected_starting_polygon';  // selected starting area for queary
export const QUERY_DESTINATION_POLYGON = 'selected_destination_polygon';  // selected destination area for queary
export const QUERY_CLUSTRING_BOUNDERY = 'query_clustering_boundery' // selected min and max clustering size
export const QUERY_MARK = 'query_mark';
export const REPORT_SELECTION =  'report_selection';
export const ERROR = 'error';
export const MESSAGE = 'message';
export const CONNECTED = 'connected';
export const UPLOAD_RESULT = 'upload_result';
export const COMPANY_EXIST = 'company_exist';
export const LOAD_RESULT_NOTIFICATION = 'load_result_notification';
export const MAP_CHANGE = 'map_change'; // saving the map position
export const DELETE_COMPANY = "delete_company";
